---
abstract: 'Catalyst based application'
author:
  - 'Wellcome Trust Sanger Institute'
build_requires:
  File::Find: 0
  File::Temp: 0
  Selenium::Firefox: 0
  Test::MockModule: 0
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0
  URI: 0
  WebAppCommon::Testing::JS: 0
  YAML: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WGE
requires:
  Bio::Perl: 0
  Bio::Seq: 0
  Bio::SeqIO: 0
  Bio::Tools::CodonTable: 0
  Carp: 0
  Catalyst: 0
  Catalyst::Authentication::Credential: 0
  Catalyst::Controller: 0
  Catalyst::Controller::REST: 0
  Catalyst::Devel: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80
  Catalyst::View::CSV: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::Any: 0
  Config::Tiny: 0
  Const::Fast: 0
  DBI: 0
  DBIx::Class::Core: 0
  DBIx::Class::ResultSet: 0
  DBIx::Class::Schema: 0
  DBIx::Class::Schema::Loader: 0
  Data::Dump: 0
  Data::Dumper: 0
  Data::Random: 0
  Data::Serializer: 0
  DateTime: 0
  DateTime::Format::Pg: 0
  Excel::Writer::XLSX: 0
  File::stat: 0
  FindBin: 0
  Getopt::Long: 0
  HTGT::QC::Util::GeneratePrimersAttempts: 0
  HTTP::Request::Common: 0
  Hash::MoreUtils: 0
  IO::File: 0
  IO::Handle: 0
  IO::String: 0
  JSON: 0
  LIMS2::Exception: 0
  LIMS2::Exception::InvalidState: 0
  LIMS2::REST::Client: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Log4perl: 0
  Log::Log4perl::Catalyst: 0
  MIME::Base64: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  MooseX::Log::Log4perl: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  MooseX::SimpleConfig: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Path::Class::MoreCoercions: 0
  MooseX::Types::URI: 0
  POSIX: 0
  Path::Class: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Smart::Comments: 0
  Sub::Exporter: 0
  Term::ReadPassword: 0
  Text::CSV: 0
  Throwable::Error: 0
  Try::Tiny: 0
  TryCatch: 0
  WebAppCommon::Crispr::SubmitInterface: 0
  WebAppCommon::Design::CreateInterface: 0
  WebAppCommon::FormValidator: 0
  WebAppCommon::FormValidator::Constraint: 0
  WebAppCommon::Util::EnsEMBL: 0
  YAML::Any: 0
  autodie: 0
  base: 0
  feature: 0
  namespace::autoclean: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.119
